INSERT INTO users (name, age) VALUES ("Khal Drogo", 31);
INSERT INTO users (name, age) VALUES ("Daenarys Targaryen", 18);
INSERT INTO users (name, age) VALUES ("John Snow", 26);
INSERT INTO users (name, age) VALUES ("Samwell Tarly", 24);
INSERT INTO users (name, age) VALUES ("Cersei Lannister", 43);
INSERT INTO users (name, age) VALUES ("Tyrion Lannister", 40);
INSERT INTO users (name, age) VALUES ("Arya Stark", 15);
INSERT INTO users (name, age) VALUES ("Sansa Stark", 18);
INSERT INTO users (name, age) VALUES ("Joffrey Baratheon", 16);
INSERT INTO users (name, age) VALUES ("Petyr Baelish", 47);
INSERT INTO users (name, age) VALUES ("Margaery Tyrell", 23);
INSERT INTO users (name, age) VALUES ("Theon Greyjoy", 20);
INSERT INTO users (name, age) VALUES ("Ramsay Bolton", 30);
INSERT INTO users (name, age) VALUES ("Bronn", 37);
INSERT INTO users (name, age) VALUES ("Jaime Lannister", 43);
INSERT INTO users (name, age) VALUES ("Ygritte", 23);
INSERT INTO users (name, age) VALUES ("Hodor", 40);
INSERT INTO users (name, age) VALUES ("Jorah Marmont", 36);
INSERT INTO users (name, age) VALUES ("Viserys Targaryen", 19);
INSERT INTO users (name, age) VALUES ("Tormund Giantsbane", 33);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pilot", "TV Show", 9000, "12/09/08", "2/05/09");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 1", "HBO", 30000, "12/09/10", "2/05/11");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 2", "HBO", 40000, "12/09/11", "2/05/12");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 3", "HBO", 50000, "12/09/12", "2/05/13");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 4", "HBO", 55000, "12/09/13", "2/05/14");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 5", "HBO", 60000, "12/09/14", "2/05/15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 6", "HBO", 70000, "12/09/15", "2/05/16");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 7", "HBO", 80000, "12/09/16", "2/05/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Season 8", "HBO", 90000, "12/09/17", "2/05/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Trailer season 8", "Trailer", 6000, "12/09/18", "2/05/19");

INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (57, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (550, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6700, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (470, 8, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8990, 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (49640, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4440, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 17, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (49000, 18, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (111140, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11140, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8040, 2, 9);
